apiVersion: v1
kind: Service
metadata:
  name: aws-heptio-kube-cloudant-cred1v3a
  labels:
    app: aws-heptio-kube-cloudant-cred1v3a
spec:
  ports:
  - port: 3000
  selector:
    app: aws-heptio-kube-cloudant-cred1v3a
  type: LoadBalancer
---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: aws-heptio-kube-cloudant-cred1v3a
  spec:
    replicas: 2
    template:
      metadata:
#        name: aws-heptio-kube-cloudant-cred1v3a
        labels:
          app: aws-heptio-kube-cloudant-cred1v3a
      spec:
        containers:
          - name: cloudant-sample
            image: 143691129248.dkr.ecr.us-west-2.amazonaws.com/cloudant:1.0.3
            ports:
              - containerPort: 3000
            env:
            - name: VCAP_SERVICES
              value: '{"cloudantNoSQLDB": [ { "credentials": { "username": "bb89ffad-5d81-4ed4-afe7-755f8e2c795c-bluemix", "password": "7892ad525130a8d071bf9cadc637edded1ecb5b530c7faa55280f7ea058183b5", "host":"bb89ffad-5d81-4ed4-afe7-755f8e2c795c-bluemix.cloudant.com", "port": 443, "url": "https://bb89ffad-5d81-4ed4-afe7-755f8e2c795c-bluemix:7892ad525130a8d071bf9cadc637edded1ecb5b530c7faa55280f7ea058183b5@bb89ffad-5d81-4ed4-afe7-755f8e2c795c-bluemix.cloudant.com" }, "syslog_drain_url": null, "label": "cloudantNoSQLDB", "provider": null, "plan": "Lite", "name": "cloudant-mike", "tags": [ "data_management", "ibm_created", "lite", "ibm_dedicated_public" ] } ] }'
